#!/bin/sh
################################################################################
#
#   Copyright(C) Jonas 'Sortie' Termansen 2013.
#
#   This file is part of Tix.
#
#   Tix is free software: you can redistribute it and/or modify it under the
#   terms of the GNU General Public License as published by the Free Software
#   Foundation, either version 3 of the License, or (at your option) any later
#   version.
#
#   Tix is distributed in the hope that it will be useful, but WITHOUT ANY
#   WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#   FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#   details.
#
#   You should have received a copy of the GNU General Public License along with
#   Tix. If not, see <https://www.gnu.org/licenses/>.
#
#   tix-eradicate-libtool-la
#   Deletes useless libtool .la files from the staging directory.
#
################################################################################

set -e
cd "$TIX_INSTALL_DIR"
find | grep '\.la$' | while read la; do rm -f "$la"; done
