#!/bin/sh -e
################################################################################
#
#   Copyright(C) Jonas 'Sortie' Termansen 2016.
#
#   This program is free software: you can redistribute it and/or modify it
#   under the terms of the GNU General Public License as published by the Free
#   Software Foundation, either version 3 of the License, or (at your option)
#   any later version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
#   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#   FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
#   more details.
#
#   You should have received a copy of the GNU General Public License along with
#   this program. If not, see <http://www.gnu.org/licenses/>.
#
#   sfnc
#   nc over sf
#
################################################################################

if [ $# != 4 ]; then
  echo Usage: $0 host port transmit-device receive-device
  exit 1
fi
(printf -- "$1\n" | sf -o &&
 printf -- "$2\n" | sf -o &&
 cat) | sf -o -- "$3" | sf -i -- "$4"
