#!/bin/sh -e
# Copyright (c) 2016 Jonas 'Sortie' Termansen.
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# sfncd
# Remote for nc over sf

if [ $# -lt 2 ] || [ 3 -lt $# ]; then
  echo Usage: $0 receive-device transmit-device [server-command]
  exit 1
fi
sf -i -- "$1" |
(export HOST=$(sf -i) &&
 export PORT=$(sf -i) &&
 (if [ $# -lt 3 ]; then
    nc -- "$HOST" "$PORT"
  else
    sh -c "$3"
  fi) | sf -o -- "$2")
