#!/bin/sh
for KERNEL in `ls /boot | grep sortix | grep bin`; do
  echo "Found Sortix kernel: $KERNEL" >&2
  INITRD=`echo "$KERNEL" | sed 's/bin/initrd/g'`
  echo "menuentry \"Sortix\" {"
  echo "\tmultiboot /boot/$KERNEL"
  echo "\tmodule /boot/$INITRD"
  echo "}"
done

